ALGORITHM:
  NAME: "SEVAL"
  SEVAL:
    TH_CLS: 10
    PI_CLS: 127
    TH_START: 0.65
    TH_END: 0.65
    TH_EMA_DECAY: 0.99
    PI_EMA_DECAY: 0.99
    ESTIM:
      APPLY: True

PERIODS:
  EVAL: 1000
  LOG: 1000

MODEL:
  NUM_CLASSES: 127
  LOSS:
    UNLABELED_LOSS: "CrossEntropyLoss"
    UNLABELED_LOSS_WEIGHT: 1.0
  DIST_ALIGN:
    APPLY: False
  NAME:
    "ResNet50_cifar"

DATASET:
  BUILDER: "build_imagenet_dataset"
  NAME: "imagenet"
  ROOT: "./data/imagenet"

  TRANSFORM:
    STRONG_AUG: True

SOLVER:
  MAX_ITER: 100000
  BASE_LR: 0.002
  OPTIM_NAME: "Adam"
  APPLY_SCHEDULER: True
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (50000, 75000,)
  GAMMA: 0.1
  WARMUP_ITERS: 2500

OUTPUT_DIR: "outputs/imagenet/fixmatch"