ALGORITHM:
  NAME: "ReMixMatch"
  CONS_RAMPUP_SCHEDULE: "linear"
  CONS_RAMPUP_ITERS_RATIO: 0.016
  REMIXMATCH:
    NUM_AUG: 2  # number of strong augmentations
    TEMPERATURE: 0.5
    MIXUP_ALPHA: 0.75
    WEIGHT_KL: 0.5  # weight for KL loss (premixup)
    WEIGHT_ROT: 0.5  # weight for rotation loss
    LABELED_STRONG_AUG: False
  CREST:
    GEN_PERIOD_STEPS: 50000  # 1 gen. = 500 steps * 100 epochs
    ALPHA: 3.0
    TMIN: 0.5
    PROGRESSIVE_ALIGN: True  # CReST+: progressive distribution alignment

MODEL:
  WITH_ROTATION_HEAD: True
  LOSS:
    LABELED_LOSS: "CrossEntropyLoss"
    UNLABELED_LOSS: "CrossEntropyLoss"
    UNLABELED_LOSS_WEIGHT: 1.5
  DIST_ALIGN:
    APPLY: False  # For \gamma_l != \gamma_u, originally we do not apply dist_align

DATASET:
  BUILDER: "build_stl10_dataset"
  NAME: "stl10"
  ROOT: "./data/stl10"
  NUM_VALID: 500
  RESOLUTION: 32
  STL10:
    NUM_LABELED_HEAD: 450
    IMB_FACTOR_L: 10
    NUM_UNLABELED_HEAD: -1
    IMB_FACTOR_UL: -1

  TRANSFORM:
    STRONG_AUG: True

SOLVER:
  MAX_ITER: 250000  # == 5gens * 100 epochs * 500 steps

OUTPUT_DIR: "outputs/stl10/remixmatch"
