ALGORITHM:
  NAME: "FixMatchCReST"
  CONFIDENCE_THRESHOLD: 0.95
  CREST:
    GEN_PERIOD_STEPS: 50000  # 1 gen. = 500 steps * 100 epochs
    ALPHA: 3.0
    TMIN: 0.5
    PROGRESSIVE_ALIGN: True  # CReST+: progressive distribution alignment

MODEL:
  LOSS:
    UNLABELED_LOSS: "CrossEntropyLoss"
    UNLABELED_LOSS_WEIGHT: 1.0
  DIST_ALIGN:
    APPLY: True

DATASET:
  BUILDER: "build_cifar10_dataset"
  NAME: "cifar10"
  ROOT: "./data/cifar10"
  NUM_VALID: 5000
  CIFAR10:
    NUM_LABELED_HEAD: 1500
    IMB_FACTOR_L: 100
    NUM_UNLABELED_HEAD: 3000
    IMB_FACTOR_UL: 100
  REVERSE_UL_DISTRIBUTION: False

  TRANSFORM:
    STRONG_AUG: True

SOLVER:
  UNLABELED_BATCH_RATIO: 2
  MAX_ITER: 250000  # == 5gens * 100 epochs * 500 steps

OUTPUT_DIR: "outputs/cifar10/fixmatch"
