ALGORITHM:
  NAME: "MeanTeacher"
  CONS_RAMPUP_SCHEDULE: "linear"
  CONS_RAMPUP_ITERS_RATIO: 0.4

MODEL:
  NUM_CLASSES: 100
  LOSS:
    UNLABELED_LOSS_WEIGHT: 50.0

DATASET:
  BUILDER: "build_cifar100_dataset"
  NAME: "cifar100"
  ROOT: "./data/cifar100"
  NUM_VALID: 5000
  CIFAR100:
    NUM_LABELED_HEAD: 150
    IMB_FACTOR_L: 10
    NUM_UNLABELED_HEAD: 300
    IMB_FACTOR_UL: 10
  REVERSE_UL_DISTRIBUTION: False

OUTPUT_DIR: "outputs/cifar100/meanteacher"
