ALGORITHM:
  NAME: "DASO"
  CONFIDENCE_THRESHOLD: 0.95
  DARP:
    APPLY: False
  DASO:
    WITH_DIST_AWARE: True
    DIST_TEMP: 0.5
    # blend pseudo-labels with fixed weight (applied only when WITH_DIST_AWARE is False).
    INTERP_ALPHA: 0.5
    PSA_LOSS_WEIGHT: 1.0  # loss weight for semantic alignment loss
  ABC:
    APPLY: False
    DASO_PSEUDO_LABEL: True  # when abc is applied, apply DASO on pseudo-labels in abc pipeline

PERIODS:
  EVAL: 500
  LOG: 500

MODEL:
  NUM_CLASSES: 200
  LOSS:
    UNLABELED_LOSS: "CrossEntropyLoss"
    UNLABELED_LOSS_WEIGHT: 1.0
  DIST_ALIGN:
    APPLY: False
  NAME:
    "ResNet"
  EMA_DECAY: 0.9
  QUEUE:
    FEAT_DIM: 2048

DATASET:
  BUILDER: "build_aves_dataset"
  NAME: "aves"
  ROOT: "./data/semi_fgvc"
  RESOLUTION: 224
  AVES:
    UL_SOURCE: "in"

  TRANSFORM:
    STRONG_AUG: True

SOLVER:
  MAX_ITER: 45000
  IMS_PER_BATCH: 32
  BASE_LR: 0.005
  APPLY_SCHEDULER: True
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (15000, 30000,)
  GAMMA: 0.1
  WARMUP_ITERS: 2500
  SGD:
    WEIGHT_DECAY: 0.0003

OUTPUT_DIR: "outputs/aves/fixmatch"
