ALGORITHM:
  NAME: "FixMatchCReST"
  CONFIDENCE_THRESHOLD: 0.95
  CREST:
    GEN_PERIOD_STEPS: 9000
    ALPHA: 3.0
    TMIN: 0.5
    PROGRESSIVE_ALIGN: True  # CReST+: progressive distribution alignment

PERIODS:
  EVAL: 500
  LOG: 500

MODEL:
  NUM_CLASSES: 200
  LOSS:
    UNLABELED_LOSS: "CrossEntropyLoss"
    UNLABELED_LOSS_WEIGHT: 1.0
  DIST_ALIGN:
    APPLY: False
  NAME:
    "ResNet"
  EMA_DECAY: 0.9

DATASET:
  BUILDER: "build_aves_dataset"
  NAME: "aves"
  ROOT: "./data/semi_fgvc"
  RESOLUTION: 224
  AVES:
    UL_SOURCE: "in"

  TRANSFORM:
    STRONG_AUG: True

SOLVER:
  MAX_ITER: 45000
  IMS_PER_BATCH: 32
  BASE_LR: 0.005
  APPLY_SCHEDULER: True
  LR_SCHEDULER_NAME: "WarmupCosineLRFixMatch"
  GAMMA: 0.1
  WARMUP_ITERS: 500
  SGD:
    WEIGHT_DECAY: 0.0003

OUTPUT_DIR: "outputs/aves/fixmatch"
